export const Routes = {
  BootScreen: "BootScreen",
  LandingScreen: "LandingScreen",
  UserSelectorScreen: "UserSelectorScreen",

  PatientLoginScreen: "PatientLoginScreen",
  PatientNavigation: "PatientNavigation",
  PatientHomeScreen: "PatientHomeScreen",
  PatientSearchScreen: "PatientSearchScreen",
  PatientBookingsScreen: "PatientBookingsScreen",
  PatientCenterScreen: "PatientCenterScreen",
  PatientConfirmScreen: "PatientConfirmScreen",
  PatientEmptyScreen: "PatientEmptyScreen",
  PatientDoctorScreen: "PatientDoctorScreen",
  PatientFormScreen: "PatientFormScreen",
  PatientProfileOnboardingScreen: "PatientProfileOnboardingScreen",
  PatientLocationScreen: "PatientLocationScreen",
  PatientOfflineScreen: "PatientOfflineScreen",
  PatientResultsScreen: "PatientResultsScreen",
  PatientSuccessScreen: "PatientSuccessScreen",
  PatientTimeScreen: "PatientTimeScreen",

  DoctorNavigation: "DoctorNavigation",
  DoctorHomeScreen: "DoctorHomeScreen",
  DoctorApptsScreen: "DoctorApptsScreen",
  DoctorPatientsScreen: "DoctorPatientsScreen",
  DoctorPatientDetailsScreen: "DoctorPatientDetailsScreen",
  DoctorProfileScreen: "DoctorProfileScreen",
  DoctorPersonalDataScreen: "DoctorPersonalDataScreen",
  DoctorWeeklyScheduleScreen: "DoctorWeeklyScheduleScreen",
  DoctorProfileOnboardingScreen: "DoctorProfileOnboardingScreen",
  DoctorLoginScreen: "DoctorLoginScreen",

  CenterNavigation: "CenterNavigation",
  CenterLoginScreen: "CenterLoginScreen",
  CenterHomeScreen: "CenterHomeScreen",
  CenterBookingsScreen: "CenterBookingsScreen",
  CenterServicesScreen: "CenterServicesScreen",
  CenterServiceFormScreen: "CenterServiceFormScreen",
  CenterServiceDetailsScreen: "CenterServiceDetailsScreen",
  CenterBasicDataScreen: "CenterBasicDataScreen",
  CenterLocationScreen: "CenterLocationScreen",
  CenterWorkingHoursScreen: "CenterWorkingHoursScreen",
  CenterProfileScreen: "CenterProfileScreen",
  CenterProfileOnboardingScreen: "CenterProfileOnboardingScreen",
};
