export const Routes = {
  BootScreen: "BootScreen",
  LandingScreen: "LandingScreen",
  UserSelectorScreen: "UserSelectorScreen",

  PatientNavigation: "PatientNavigation",
  PatientHomeScreen: "PatientHomeScreen",
  PatientSearchScreen: "PatientSearchScreen",
  PatientBookingsScreen: "PatientBookingsScreen",
  PatientCenterScreen: "PatientCenterScreen",
  PatientConfirmScreen: "PatientConfirmScreen",
  PatientEmptyScreen: "PatientEmptyScreen",
  PatientDoctorScreen: "PatientDoctorScreen",
  PatientFormScreen: "PatientFormScreen",
  PatientLocationScreen: "PatientLocationScreen",
  PatientOfflineScreen: "PatientOfflineScreen",
  PatientResultsScreen: "PatientResultsScreen",
  PatientSuccessScreen: "PatientSuccessScreen",
  PatientTimeScreen: "PatientTimeScreen",

  DoctorNavigation: "DoctorNavigation",
  DoctorHomeScreen: "DoctorHomeScreen",
  DoctorApptsScreen: "DoctorApptsScreen",
  DoctorPatientsScreen: "DoctorPatientsScreen",
  DoctorProfileScreen: "DoctorProfileScreen",
  DoctorLoginScreen: "DoctorLoginScreen",

  CenterNavigation: "CenterNavigation",
  CenterLoginScreen: "CenterLoginScreen",
  CenterHomeScreen: "CenterHomeScreen",
  CenterBookingsScreen: "CenterBookingsScreen",
  CenterServicesScreen: "CenterServicesScreen",
  CenterProfileScreen: "CenterProfileScreen",
};
